receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555
  filelog:
    include: [ "/var/log/observable-spring-boot-app.log" ]

processors:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: log.file.name
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: collector:6666
    namespace: default
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp ]
    logs:
      receivers: [ filelog ]
      processors: [ attributes ]
      exporters: [ loki ]
  telemetry:
    logs:
      level: debug